### ISSUE TITLE
dmarc-convertor.sh only does zip attachments, skips gzip

### ISSUE THREAD

**Issue by chiefthunderpants** [prbinu/dmarc-report-processor#7]
In dmarc-convertor.sh "files" variable is coded to only *.zip. 

Change 
`files=( "${ATTACH}/${ydate}"/*.zip )`
to
`files=( "${ATTACH}/${ydate}"/* )`
and it will work on both.

**Comment by prbinu** [comment]
Thanks for the patch. Fixed the code
