### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by DanMcGuinness** [prbinu/dmarc-report-processor#8]
I can't work out how to get a CSV output from the script. All I get a log files. Help please :)

**Comment by prbinu** [comment]
Please provide more details:
1. input file used
2. command  and parameters
3. the output you got.

**Comment by DanMcGuinness** [comment]
I'm using Dmarc-converter.sh. I've edited the script and this is the 'fetch from imap' piece:

${ROOT}/bin/imap-client.py --attachmentsonly -s "${d_host}" -c "${d_cert}" --port "${d_port}"  -u "${d_user}" -o ${ATTACH}/${ydate} -f inbox --pwdfile "${d_pwd}" -S "${d_search}"

The mails are fetched correctly and xml files are processed. My problem is I get a something.log file output in dmarc_splunk for each xml file. There's no CSV present. I've not edited the parsing line in the script: 

${ROOT}/bin/dmarc-parser.py ${f} > "${DMARC_SPLUNK}/${ydate}/${fname%.*}.log"

Is that the information you need? Thanks!

**Comment by prbinu** [comment]
Did you check the log file content? I presume that is the output file you are looking for.

**Comment by DanMcGuinness** [comment]
The log file contains a line of data for each email, but the lines are of the format:

org_name=Yahoo! Inc., email=postmaster@dmarc.yahoo.com, extra_contact_info=NULL, date_range_begin=1543968000, date_range_end=1544054399 , domain=domain.com, adkim=r, aspf=r, p=none, pct=1, source_ip=10.10.10.10, count=1, disposition=none, dkim=fail, spf=fail, reason_type=NULL, comment=NULL, envelope_to=NULL, header_from=domain.com, dkim_domain=otherdomain.com, dkim_result=pass, dkim_hresult=NULL, spf_domain=domain.com, spf_result=softfail, x-host_name=NULL

I was expecting a CSV with a 'top' line containing the heading and each subsequent line to contain the values. 

If the tool doesn't do that, that's fine. I was just expecting a CSV from what the instructions say and this looks like something different.

**Comment by prbinu** [comment]
yeah, you are right. This is not CSV, it is comma-separated key-value format. I have updated the project heading to reflect it.
